In [29]:
#import liberary
import numpy as np
import pandas as pd

In [30]:
#import file csv
data = pd.read_csv('Automobile.csv')
data.dropna(inplace=True)
#choose columns
data=data[['company','wheel-base','length','horsepower','average-mileage','price']]
data.head()

       company  wheel-base  length  horsepower  average-mileage    price
0  alfa-romero        88.6   168.8         111               21  13495.0
1  alfa-romero        88.6   168.8         111               21  16500.0
2  alfa-romero        94.5   171.2         154               19  16500.0
3         audi        99.8   176.6         102               24  13950.0
4         audi        99.4   176.6         115               18  17450.0

In [69]:
#crate class to convert dataframe to numpy array
class Con:
    def __init__(self,value):
        self.value = value
    
    def convert(self):
        self.df =pd.DataFrame(self.value)
        self.df =self.df.to_numpy()
        return self.df

# create class to calculate min-max and z-score normalization
class Nor:
    def __init__(self,num):
        self.num = num

    def minmax(self): #min-max normalization
        min_max=[]
        min = np.min(self.num)
        max = np.max(self.num)
        
        for i in self.num:
            self.nor = (i-min)/(max-min)
            min_max.append(self.nor)
            
        return min_max
    
    def zscore(self): #z-score normalization
        mean =np.mean(self.num)
        std =np.std(self.num)
        outline =[]
        for i2 in self.num:
            self.ans=(i2-mean)/std
            outline.append(self.ans)
        return outline

# create class to convert numpy array to dataframe
class Get:
    
    def __init__(self,normal,score):
        self.normal = normal
        self.score = score
    
    def create(self):
        dataframe = {'min-max':self.normal,'zscore':self.score}
        df_new = pd.DataFrame(dataframe)
        print(df_new)

In [70]:
# create function to get result 
def fw(x):
    result = Con(x)
    normal =Nor(result.convert())
    frame=Get(normal.minmax(),normal.zscore())
    com = frame.create()
    combine = pd.concat([data['company'],x,com], axis=1, join='inner')
    print(combine)
    
wheel=fw(data['wheel-base'])

                   min-max                  zscore
0   [0.006153846153845804]   [-1.4841899719621627]
1   [0.006153846153845804]   [-1.4841899719621627]
2    [0.18769230769230752]   [-0.6103258831709509]
3     [0.3507692307692305]   [0.17467067116691626]
4     [0.3384615384615385]   [0.11542564819802185]
5     [0.3507692307692305]   [0.17467067116691626]
6     [0.5353846153846151]    [1.0633460157003511]
7    [0.39384615384615373]    [0.3820282515580519]
8    [0.39384615384615373]    [0.3820282515580519]
9    [0.39384615384615373]    [0.3820282515580519]
10   [0.46461538461538443]    [0.7226871336292016]
11   [0.46461538461538443]    [0.7226871336292016]
12    [0.6646153846153844]    [1.6854187568737562]
13                   [0.0]    [-1.513812483446609]
14   [0.18769230769230752]   [-0.6103258831709509]
15   [0.18769230769230752]   [-0.6103258831709509]
16   [0.16307692307692298]   [-0.7288159291087418]
17   [0.16307692307692298]   [-0.7288159291087418]
18   [0.24923076923076906]  [-0.31410076832647255]
19   [0.24923076923076906]  [-0.31410076832647255]
20   [0.24923076923076906]  [-0.31410076832647255]
21    [0.1815384615384613]   [-0.6399483946553991]
22    [0.7569230769230767]     [2.129756429140474]
23    [0.7569230769230767]     [2.129756429140474]
24    [0.4184615384615383]    [0.5005182974958429]
25   [0.14461538461538426]   [-0.8176834635620865]
26   [0.14461538461538426]   [-0.8176834635620865]
27   [0.14461538461538426]   [-0.8176834635620865]
28   [0.21230769230769206]     [-0.49183583723316]
29    [0.5076923076923077]    [0.9300447140203373]
30    [0.6646153846153844]    [1.6854187568737562]
31    [0.6646153846153844]    [1.6854187568737562]
32                   [1.0]     [3.299845632776164]
33    [0.7261538461538459]    [1.9816438717182345]
34   [0.16307692307692298]   [-0.7288159291087418]
35   [0.16307692307692298]   [-0.7288159291087418]
36    [0.2430769230769228]   [-0.3437232798109208]
37    [0.2430769230769228]   [-0.3437232798109208]
38   [0.18769230769230752]   [-0.6103258831709509]
39   [0.18769230769230752]   [-0.6103258831709509]
40   [0.18769230769230752]   [-0.6103258831709509]
41   [0.18769230769230752]   [-0.6103258831709509]
42   [0.36923076923076925]   [0.26353820562026103]
43   [0.03384615384615367]   [-1.3508886702821468]
44   [0.03384615384615367]   [-1.3508886702821468]
45   [0.22461538461538452]   [-0.4325908142642635]
46   [0.22461538461538452]   [-0.4325908142642635]
47   [0.22461538461538452]   [-0.4325908142642635]
48   [0.22461538461538452]   [-0.4325908142642635]
49   [0.22461538461538452]   [-0.4325908142642635]
50   [0.22461538461538452]   [-0.4325908142642635]
51    [0.4953846153846152]    [0.8707996910514407]
52    [0.2738461538461536]  [-0.19561072238868166]
53    [0.2738461538461536]  [-0.19561072238868166]
54    [0.2738461538461536]  [-0.19561072238868166]
55    [0.2738461538461536]  [-0.19561072238868166]
56   [0.48923076923076897]    [0.8411771795669925]
57   [0.48923076923076897]    [0.8411771795669925]
          company  wheel-base
0     alfa-romero        88.6
1     alfa-romero        88.6
2     alfa-romero        94.5
3            audi        99.8
4            audi        99.4
5            audi        99.8
6            audi       105.8
7             bmw       101.2
8             bmw       101.2
9             bmw       101.2
10            bmw       103.5
11            bmw       103.5
12            bmw       110.0
13      chevrolet        88.4
14      chevrolet        94.5
15      chevrolet        94.5
16          dodge        93.7
17          dodge        93.7
18          honda        96.5
19          honda        96.5
20          honda        96.5
21          isuzu        94.3
24         jaguar       113.0
25         jaguar       113.0
26         jaguar       102.0
27          mazda        93.1
28          mazda        93.1
29          mazda        93.1
30          mazda        95.3
31          mazda       104.9
32  mercedes-benz       110.0
33  mercedes-benz       110.0
34  mercedes-benz       120.9
35  mercedes-benz       112.0
36     mitsubishi        93.7
37     mitsubishi        93.7
38     mitsubishi        96.3
39     mitsubishi        96.3
40         nissan        94.5
41         nissan        94.5
42         nissan        94.5
43         nissan        94.5
44         nissan       100.4
45        porsche        89.5
46        porsche        89.5
48         toyota        95.7
49         toyota        95.7
50         toyota        95.7
51         toyota        95.7
52         toyota        95.7
53         toyota        95.7
54         toyota       104.5
55     volkswagen        97.3
56     volkswagen        97.3
57     volkswagen        97.3
58     volkswagen        97.3
59          volvo       104.3
60          volvo       104.3

In [60]:
length=fw(data['length'])

                  min-max                  zscore
0    [0.4134328358208958]  [-0.34906573382856376]
1    [0.4134328358208958]  [-0.34906573382856376]
2    [0.4492537313432835]   [-0.1762092765217844]
3    [0.5298507462686567]   [0.21271775241847327]
4    [0.5298507462686567]   [0.21271775241847327]
5    [0.5402985074626868]   [0.26313421913295226]
6    [0.7701492537313432]     [1.372296486851462]
7    [0.5328358208955226]    [0.2271224571940396]
8    [0.5328358208955226]    [0.2271224571940396]
9    [0.5328358208955226]    [0.2271224571940396]
10   [0.7149253731343285]    [1.1058094485035088]
11   [0.7865671641791048]    [1.4515223631170717]
12   [0.8343283582089553]    [1.6819976395261123]
13                  [0.0]    [-2.344117345244329]
14  [0.22089552238805987]    [-1.278169191852512]
15  [0.26417910447761217]    [-1.069300972606818]
16  [0.24179104477611965]    [-1.177336258423556]
17  [0.24179104477611965]    [-1.177336258423556]
18  [0.23880597014925373]   [-1.1917409631991223]
19   [0.5119402985074628]    [0.1262895237650836]
20    [0.417910447761194]  [-0.32745867666521733]
21   [0.4417910447761193]   [-0.2122210384606971]
22   [0.8731343283582089]     [1.869258801608458]
23   [0.8731343283582089]     [1.869258801608458]
24   [0.7552238805970148]    [1.3002729629736367]
25  [0.26865671641791045]   [-1.0476939154434715]
26  [0.26865671641791045]   [-1.0476939154434715]
27  [0.26865671641791045]   [-1.0476939154434715]
28   [0.4164179104477613]   [-0.3346610290529995]
29   [0.5059701492537314]   [0.09748011421395301]
30   [0.7432835820895524]    [1.2426541438713776]
31   [0.7432835820895524]    [1.2426541438713776]
32                  [1.0]     [2.481458754569974]
33   [0.8671641791044775]    [1.8404493920573273]
34  [0.24179104477611965]    [-1.177336258423556]
35  [0.24179104477611965]    [-1.177336258423556]
36   [0.4671641791044778]  [-0.08978104786839267]
37   [0.4671641791044778]  [-0.08978104786839267]
38   [0.3611940298507465]   [-0.6011480674009527]
39   [0.3611940298507465]   [-0.6011480674009527]
40   [0.3611940298507465]   [-0.6011480674009527]
41  [0.43432835820895516]   [-0.2482328003996098]
42   [0.6492537313432836]    [0.7889059434410766]
43  [0.41492537313432853]   [-0.3418633814407816]
44  [0.41492537313432853]   [-0.3418633814407816]
45  [0.26268656716417904]    [-1.076503324994602]
46  [0.26268656716417904]    [-1.076503324994602]
47  [0.26268656716417904]    [-1.076503324994602]
48  [0.42686567164179096]   [-0.2842445623385225]
49  [0.42686567164179096]   [-0.2842445623385225]
50  [0.42686567164179096]   [-0.2842445623385225]
51   [0.6970149253731346]     [1.019381219850119]
52   [0.4567164179104477]   [-0.1401975145828717]
53   [0.4567164179104477]   [-0.1401975145828717]
54   [0.4567164179104477]   [-0.1401975145828717]
55   [0.4567164179104477]   [-0.1401975145828717]
56    [0.711940298507463]    [1.0914047437279446]
57    [0.711940298507463]    [1.0914047437279446]
          company  length
0     alfa-romero   168.8
1     alfa-romero   168.8
2     alfa-romero   171.2
3            audi   176.6
4            audi   176.6
5            audi   177.3
6            audi   192.7
7             bmw   176.8
8             bmw   176.8
9             bmw   176.8
10            bmw   189.0
11            bmw   193.8
12            bmw   197.0
13      chevrolet   141.1
14      chevrolet   155.9
15      chevrolet   158.8
16          dodge   157.3
17          dodge   157.3
18          honda   157.1
19          honda   175.4
20          honda   169.1
21          isuzu   170.7
24         jaguar   199.6
25         jaguar   199.6
26         jaguar   191.7
27          mazda   159.1
28          mazda   159.1
29          mazda   159.1
30          mazda   169.0
31          mazda   175.0
32  mercedes-benz   190.9
33  mercedes-benz   190.9
34  mercedes-benz   208.1
35  mercedes-benz   199.2
36     mitsubishi   157.3
37     mitsubishi   157.3
38     mitsubishi   172.4
39     mitsubishi   172.4
40         nissan   165.3
41         nissan   165.3
42         nissan   165.3
43         nissan   170.2
44         nissan   184.6
45        porsche   168.9
46        porsche   168.9
48         toyota   158.7
49         toyota   158.7
50         toyota   158.7
51         toyota   169.7
52         toyota   169.7
53         toyota   169.7
54         toyota   187.8
55     volkswagen   171.7
56     volkswagen   171.7
57     volkswagen   171.7
58     volkswagen   171.7
59          volvo   188.8
60          volvo   188.8

In [61]:
horsepower=fw(data['horsepower'])

                   min-max                  zscore
0    [0.29439252336448596]   [0.10204338178783681]
1    [0.29439252336448596]   [0.10204338178783681]
2     [0.4953271028037383]    [0.9887897029685507]
3     [0.2523364485981308]  [-0.08355468543603355]
4     [0.3130841121495327]   [0.18453141166511253]
5     [0.2897196261682243]   [0.08142137431851788]
6     [0.2897196261682243]   [0.08142137431851788]
7    [0.24766355140186916]  [-0.10417669290535247]
8    [0.24766355140186916]  [-0.10417669290535247]
9     [0.3411214953271028]    [0.3082634564810261]
10    [0.6261682242990654]    [1.5662059121094807]
11    [0.6261682242990654]    [1.5662059121094807]
12    [0.6261682242990654]    [1.5662059121094807]
13                   [0.0]   [-1.1971430887792558]
14     [0.102803738317757]   [-0.7434589244542392]
15     [0.102803738317757]   [-0.7434589244542392]
16   [0.09345794392523364]   [-0.7847029393928772]
17   [0.09345794392523364]   [-0.7847029393928772]
18    [0.1308411214953271]   [-0.6197268796383257]
19   [0.24766355140186916]  [-0.10417669290535247]
20   [0.24299065420560748]   [-0.1247987003746714]
21   [0.14018691588785046]   [-0.5784828646996878]
22    [0.5981308411214953]     [1.442473867293567]
23    [0.5981308411214953]     [1.442473867293567]
24                   [1.0]     [3.215966509654995]
25   [0.09345794392523364]   [-0.7847029393928772]
26   [0.09345794392523364]   [-0.7847029393928772]
27   [0.09345794392523364]   [-0.7847029393928772]
28   [0.24766355140186916]  [-0.10417669290535247]
29   [0.11214953271028037]   [-0.7022149095156014]
30   [0.35046728971962615]     [0.349507471419664]
31   [0.35046728971962615]     [0.349507471419664]
32    [0.6355140186915887]    [1.6074499270481186]
33    [0.6355140186915887]    [1.6074499270481186]
34   [0.09345794392523364]   [-0.7847029393928772]
35   [0.09345794392523364]   [-0.7847029393928772]
36   [0.18691588785046728]  [-0.37226279000649853]
37   [0.18691588785046728]  [-0.37226279000649853]
38   [0.03271028037383177]   [-1.0527890364940231]
39   [0.09813084112149532]   [-0.7640809319235582]
40   [0.09813084112149532]   [-0.7640809319235582]
41   [0.09813084112149532]   [-0.7640809319235582]
42   [0.48598130841121495]    [0.9475456880299129]
43    [0.7429906542056075]     [2.081756098842454]
44    [0.7429906542056075]     [2.081756098842454]
45   [0.06542056074766354]   [-0.9084349842087907]
46   [0.06542056074766354]   [-0.9084349842087907]
47   [0.06542056074766354]   [-0.9084349842087907]
48   [0.06542056074766354]   [-0.9084349842087907]
49   [0.06542056074766354]   [-0.9084349842087907]
50   [0.06542056074766354]   [-0.9084349842087907]
51    [0.5046728971962616]    [1.0300337179071886]
52  [0.018691588785046728]     [-1.11465505890198]
53   [0.17289719626168223]  [-0.43412881241445533]
54  [0.018691588785046728]     [-1.11465505890198]
55   [0.24299065420560748]   [-0.1247987003746714]
56     [0.308411214953271]    [0.1639094041957936]
57     [0.308411214953271]    [0.1639094041957936]
          company  horsepower
0     alfa-romero         111
1     alfa-romero         111
2     alfa-romero         154
3            audi         102
4            audi         115
5            audi         110
6            audi         110
7             bmw         101
8             bmw         101
9             bmw         121
10            bmw         182
11            bmw         182
12            bmw         182
13      chevrolet          48
14      chevrolet          70
15      chevrolet          70
16          dodge          68
17          dodge          68
18          honda          76
19          honda         101
20          honda         100
21          isuzu          78
24         jaguar         176
25         jaguar         176
26         jaguar         262
27          mazda          68
28          mazda          68
29          mazda          68
30          mazda         101
31          mazda          72
32  mercedes-benz         123
33  mercedes-benz         123
34  mercedes-benz         184
35  mercedes-benz         184
36     mitsubishi          68
37     mitsubishi          68
38     mitsubishi          88
39     mitsubishi          88
40         nissan          55
41         nissan          69
42         nissan          69
43         nissan          69
44         nissan         152
45        porsche         207
46        porsche         207
48         toyota          62
49         toyota          62
50         toyota          62
51         toyota          62
52         toyota          62
53         toyota          62
54         toyota         156
55     volkswagen          52
56     volkswagen          85
57     volkswagen          52
58     volkswagen         100
59          volvo         114
60          volvo         114

In [62]:
average=fw(data['average-mileage'])

                   min-max                  zscore
0    [0.23529411764705882]   [-0.5766476277375624]
1    [0.23529411764705882]   [-0.5766476277375624]
2    [0.17647058823529413]   [-0.8309865053708599]
3     [0.3235294117647059]  [-0.19513931128761625]
4    [0.14705882352941177]   [-0.9581559441875086]
5    [0.17647058823529413]   [-0.8309865053708599]
6    [0.17647058823529413]   [-0.8309865053708599]
7    [0.29411764705882354]  [-0.32230875010426496]
8    [0.29411764705882354]  [-0.32230875010426496]
9    [0.23529411764705882]   [-0.5766476277375624]
10   [0.08823529411764706]    [-1.212494821820806]
11   [0.08823529411764706]    [-1.212494821820806]
12  [0.058823529411764705]    [-1.339664260637455]
13                   [1.0]    [2.7297577814953047]
14    [0.7352941176470589]     [1.585232832145466]
15    [0.7352941176470589]     [1.585232832145466]
16    [0.5294117647058824]    [0.6950467604289249]
17    [0.5294117647058824]    [0.6950467604289249]
18                   [0.5]    [0.5678773216122761]
19    [0.3235294117647059]  [-0.19513931128761625]
20   [0.35294117647058826]  [-0.06796987247096752]
21    [0.3235294117647059]  [-0.19513931128761625]
22  [0.058823529411764705]    [-1.339664260637455]
23  [0.058823529411764705]    [-1.339664260637455]
24                   [0.0]   [-1.5940031382707522]
25                   [0.5]    [0.5678773216122761]
26    [0.5294117647058824]    [0.6950467604289249]
27    [0.5294117647058824]    [0.6950467604289249]
28   [0.11764705882352941]   [-1.0853253830041574]
29    [0.5294117647058824]    [0.6950467604289249]
30    [0.2647058823529412]  [-0.44947818892091373]
31    [0.2647058823529412]  [-0.44947818892091373]
32  [0.029411764705882353]   [-1.4668336994541036]
33  [0.029411764705882353]   [-1.4668336994541036]
34    [0.7058823529411765]    [1.4580633933288172]
35    [0.5294117647058824]    [0.6950467604289249]
36   [0.35294117647058826]  [-0.06796987247096752]
37   [0.35294117647058826]  [-0.06796987247096752]
38    [0.9411764705882353]     [2.475418903862007]
39    [0.5294117647058824]    [0.6950467604289249]
40    [0.5294117647058824]    [0.6950467604289249]
41    [0.5294117647058824]    [0.6950467604289249]
42   [0.17647058823529413]   [-0.8309865053708599]
43   [0.11764705882352941]   [-1.0853253830041574]
44   [0.11764705882352941]   [-1.0853253830041574]
45    [0.6470588235294118]    [1.2037245156955199]
46    [0.5294117647058824]    [0.6950467604289249]
47    [0.5294117647058824]    [0.6950467604289249]
48    [0.5294117647058824]    [0.6950467604289249]
49    [0.4117647058823529]   [0.18636900516232993]
50    [0.4117647058823529]   [0.18636900516232993]
51   [0.17647058823529413]   [-0.8309865053708599]
52    [0.7058823529411765]    [1.4580633933288172]
53    [0.4117647058823529]   [0.18636900516232993]
54    [0.7058823529411765]    [1.4580633933288172]
55   [0.38235294117647056]  [0.059199566345681215]
56   [0.29411764705882354]  [-0.32230875010426496]
57   [0.29411764705882354]  [-0.32230875010426496]
          company  average-mileage
0     alfa-romero               21
1     alfa-romero               21
2     alfa-romero               19
3            audi               24
4            audi               18
5            audi               19
6            audi               19
7             bmw               23
8             bmw               23
9             bmw               21
10            bmw               16
11            bmw               16
12            bmw               15
13      chevrolet               47
14      chevrolet               38
15      chevrolet               38
16          dodge               31
17          dodge               31
18          honda               30
19          honda               24
20          honda               25
21          isuzu               24
24         jaguar               15
25         jaguar               15
26         jaguar               13
27          mazda               30
28          mazda               31
29          mazda               31
30          mazda               17
31          mazda               31
32  mercedes-benz               22
33  mercedes-benz               22
34  mercedes-benz               14
35  mercedes-benz               14
36     mitsubishi               37
37     mitsubishi               31
38     mitsubishi               25
39     mitsubishi               25
40         nissan               45
41         nissan               31
42         nissan               31
43         nissan               31
44         nissan               19
45        porsche               17
46        porsche               17
48         toyota               35
49         toyota               31
50         toyota               31
51         toyota               31
52         toyota               27
53         toyota               27
54         toyota               19
55     volkswagen               37
56     volkswagen               27
57     volkswagen               37
58     volkswagen               26
59          volvo               23
60          volvo               23

In [63]:
price=fw(data['price'])

                    min-max                   zscore
0     [0.20730949837263038]   [-0.16859368582899867]
1     [0.28196973837859324]    [0.09917799805902512]
2     [0.28196973837859324]    [0.09917799805902512]
3     [0.21861412705905736]   [-0.12804922121367393]
4      [0.3055728092623419]    [0.18383127582728556]
5     [0.25091306616313447]  [-0.012207893741317557]
6     [0.34209545578772144]    [0.31482108458448854]
7     [0.28023056473452757]    [0.09294038811820593]
8     [0.29252900693184924]    [0.13704920127114162]
9      [0.3930283982210738]    [0.49749394713705053]
10     [0.6362642550125469]     [1.3698682517173344]
11     [0.8985067951998807]      [2.310410722079428]
12     [0.7883177221794331]      [1.915213577971812]
13                    [0.0]    [-0.9121167907746461]
14   [0.028423066411587865]    [-0.8101764225989725]
15    [0.03537976098785063]    [-0.7852259828356957]
16   [0.030460384108921962]      [-0.80286950809687]
17   [0.026783274118611644]    [-0.8160575976860306]
18    [0.05326840418395488]    [-0.7210677091586983]
19    [0.19364456259782853]   [-0.21760347822114945]
20     [0.1290466843896743]    [-0.4492861331658622]
21   [0.040597281920047704]    [-0.7665131530132382]
22     [0.6732838082933738]     [1.5026402347433427]
23     [0.7552734229421849]     [1.7966989890962475]
24       [0.76645382493975]     [1.8367979101443708]
25  [0.0010931948619841486]     [-0.908196007383274]
26   [0.023453998857114463]    [-0.8279981652870273]
27    [0.04084573529777137]    [-0.7656220658788354]
28     [0.1663146910482248]     [-0.315623063005451]
29    [0.32778454123083806]    [0.26349446564289064]
30     [0.5068697358940595]     [0.9057900721203866]
31     [0.5738527665283609]     [1.1460271635553658]
32     [0.8896867002906904]     [2.2787771288081307]
33                    [1.0]      [2.674419816482948]
34   [0.005913190389823349]    [-0.8909089169758608]
35    [0.02578946060771696]    [-0.8196219462236416]
36   [0.045665730825610575]    [-0.7483349754714222]
37      [0.075480136152451]    [-0.6414045193430933]
38   [0.048398717980570945]    [-0.7385330169929921]
39    [0.03721831598300579]    [-0.7786319380411154]
40   [0.042187383537479195]    [-0.7608101953530606]
41     [0.0546100524236627]    [-0.7162558386329235]
42    [0.20740887972371985]    [-0.1682372509752376]
43     [0.7174588188526423]     [1.6610755272401503]
44     [0.7919948321697433]     [1.9284016675609728]
45   [0.004894531541156302]    [-0.8945623742269121]
46   [0.029491415935799646]    [-0.8063447479210407]
47     [0.0332182166016547]    [-0.7929784409049996]
48    [0.04390171184377251]    [-0.7546616941256817]
49     [0.0682501428606922]     [-0.667335154954213]
50    [0.09011404010037516]    [-0.5889194871267718]
51      [0.263335735049318]    [0.03234646297881951]
52    [0.06519416631469105]    [-0.6782955267073667]
53    [0.07016323386916445]    [-0.6604737840193119]
54    [0.07066014062461179]    [-0.6586916097505064]
55    [0.12035081616934583]    [-0.4804741828699582]
56     [0.1935203359089667]    [-0.2180490217883508]
57      [0.205321871350841]    [-0.1757223829042206]
          company    price
0     alfa-romero  13495.0
1     alfa-romero  16500.0
2     alfa-romero  16500.0
3            audi  13950.0
4            audi  17450.0
5            audi  15250.0
6            audi  18920.0
7             bmw  16430.0
8             bmw  16925.0
9             bmw  20970.0
10            bmw  30760.0
11            bmw  41315.0
12            bmw  36880.0
13      chevrolet   5151.0
14      chevrolet   6295.0
15      chevrolet   6575.0
16          dodge   6377.0
17          dodge   6229.0
18          honda   7295.0
19          honda  12945.0
20          honda  10345.0
21          isuzu   6785.0
24         jaguar  32250.0
25         jaguar  35550.0
26         jaguar  36000.0
27          mazda   5195.0
28          mazda   6095.0
29          mazda   6795.0
30          mazda  11845.0
31          mazda  18344.0
32  mercedes-benz  25552.0
33  mercedes-benz  28248.0
34  mercedes-benz  40960.0
35  mercedes-benz  45400.0
36     mitsubishi   5389.0
37     mitsubishi   6189.0
38     mitsubishi   6989.0
39     mitsubishi   8189.0
40         nissan   7099.0
41         nissan   6649.0
42         nissan   6849.0
43         nissan   7349.0
44         nissan  13499.0
45        porsche  34028.0
46        porsche  37028.0
48         toyota   5348.0
49         toyota   6338.0
50         toyota   6488.0
51         toyota   6918.0
52         toyota   7898.0
53         toyota   8778.0
54         toyota  15750.0
55     volkswagen   7775.0
56     volkswagen   7975.0
57     volkswagen   7995.0
58     volkswagen   9995.0
59          volvo  12940.0
60          volvo  13415.0

In [64]:
#export csv file
dff=pd.DataFrame(price)
dff.to_csv('newprice.csv')

In [57]:
#test a file
new =pd.read_csv('newprice.csv')
new

Empty DataFrame
Columns: [Unnamed: 0]
Index: []